dense_features:
    dtype: "double"
    model:
        name: "k2scnn"
    sparse : True
    max_edge : 1024
    patch_size : 11
mapping:
    dense_features: ${..dense_features}
    KA:
        apply: true
        strategy: "keypt2subpx"
        level_indices: null
        max_kps_per_problem: 50
        optimizer:
            print_summary: false
    BA:
        apply: false
localization:
    dense_features: ${..dense_features}
    target_reference: "nearest"
    unique_inliers: "min_error"
    overwrite_features_sparse: False
    QKA:
        apply: true
        level_indices: null
        feature_inlier_thresh: -1
        optimizer:
            print_summary: false
    QBA:
        apply: true
        level_indices: null
        optimizer:
            print_summary: false
            refine_focal_length: false
            refine_extra_params: false